name: PR Title Lint

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  prtitle:
    name: Validate PR title
    runs-on: ubuntu-20.04
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
